### ISSUE TITLE
Error while running enrollAdmin.js

### ISSUE THREAD

**Issue by jkananth** [IBM/customer-loyalty-program-hyperledger-fabric-VSCode#17]
**I am getting this error when running enrollAdmin.js.  Is there an alternative way to enroll??** 

2020-02-17T07:00:35.557Z - error: [FabricCAClientService.js]: Failed to enroll admin, error:%o message=Enrollment failed with errors [undefined], stack=Error: Enrollment failed with errors [undefined]
    at IncomingMessage.response.on (/Users/a667911/Developer/Loyalty/customer-loyalty-program-hyperledger-fabric-VSCode/web-app/node_modules/fabric-ca-client/lib/FabricCAClient.js:470:22)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error Error: Enrollment failed with errors [undefined]
Failed to enroll admin user admin: ${error}

**Comment by RabiRoshan** [comment]
having the same issue...

**Comment by sandhya-nayak** [comment]
@jkananth @RabiRoshan 

Can you update the enrollAdmin.js file as per the changes in this PR: #18 and try running it again. That should display the actual error instead of the "${error}" in the last line of the output that @jkananth has provided.

Please paste that error here so we can investigate.

Please also provide the versions that you are using for the following:
- VSCode
- IBM Blockchain Platform extension for VSCode
- node
- npm

**Comment by hasanovicmina** [comment]
Hi, I have the same problem. I get the same error as mentioned. By updating the code in enrollAdmin.js, this is the last line of the error - Failed to enroll admin user admin: Error: Enrollment failed with errors [undefined].
Here are the versions:
node : 8.9.0
npm : 6.13.7
VScode: 1.42.1
IBM Blockchain Platform extension : 1.0.20

**Comment by RabiRoshan** [comment]
> @jkananth @RabiRoshan
> 
> Can you update the enrollAdmin.js file as per the changes in this PR: #18 and try running it again. That should display the actual error instead of the "${error}" in the last line of the output that @jkananth has provided.
> 
> Please paste that error here so we can investigate.
> 
> Please also provide the versions that you are using for the following:
> 
> * VSCode
> * IBM Blockchain Platform extension for VSCode
> * node
> * npm

`npm version 6.13.4`
`node version 8.17.0`
`IBM extension version 1.0.20`
`VScode version 1.42.1`

**ERROR:**
`2020-02-29T09:59:15.858Z - error: [FabricCAClientService.js]: Failed to enroll admin, error:%o message=Enrollment failed with errors [undefined], stack=Error: Enrollment failed with errors [undefined]
    at IncomingMessage.response.on (/Users/rabiroshan/Projects/customer-loyalty-program-hyperledger-fabric-VSCode-master/web-app/node_modules/fabric-ca-client/lib/FabricCAClient.js:470:22)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
Failed to enroll admin user admin: Error: Enrollment failed with errors [undefined]`

I tried to console.log in `FabricCAClient.js` and got this:
`{ error: 'unauthorized',
  reason: 'Name or password is incorrect.' }`

**Comment by RabiRoshan** [comment]
Any updates regarding this? @sandhya-nayak

**Comment by edwardceballos** [comment]
any updates?

**Comment by RabiRoshan** [comment]
> any updates?

I removed my node and npm.
Removed all of vscode files.

Installed base recommended versions of node, npm and vscode.
It is working for now.

NB: I know this is not a good way to make it work. If anyone finds a better solution, please share.✌️

**Comment by ZackWhiteIT** [comment]
Similar error for me.  I tried to resolve this by uninstalling the IBM plugin, performing a complete teardown of the Fabric network, and deleting the DataCache in VSCode. I started getting the error after upgrading the smart contract.

## SysInfo
```
vscode version 1.43.2

node version 10.18.1

npm version 6.13.4
```

## Fabric Network
.
<img width="171" alt="2020-03-25 09_12_13- Visual Studio Code" src="https://user-images.githubusercontent.com/4070869/77540047-d19bc900-6e78-11ea-98fd-1d6e52ad492a.png">

## Error
```
\web-app> node .\enrollAdmin.js


Wallet path: .\web-app\wallet

2020-03-25T13:10:34.935Z - error: [FabricCAClientService.js]: Failed to enroll admin, error:%o message=Enrollment failed with errors [undefined], stack=Error: Enrollment failed with errors [undefined]
    at IncomingMessage.response.on (.\web-app\node_modules\fabric-ca-client\lib\FabricCAClient.js:470:22)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Failed to enroll admin user admin: Error: Enrollment failed with errors [undefined]
```

**Comment by Reffx** [comment]
@sandhya-nayak 
@edwardceballos 
Was someone able to resolve it?

@RabiRoshan 
Which versions of of node, npm and vscode do you exactly use now?

**Comment by BayramAnnakov** [comment]
I was able to resolve this by exporting connection profile (Fabric Gateways --> Export Connection Profile)

and veryfying connection settings, in my case the port for certificateAuthorities was 17054, but should have been 17062 from exported connection profile

hope it helps

**Comment by premchelliah** [comment]
> I was able to resolve this by exporting connection profile (Fabric Gateways --> Export Connection Profile)
> 
> and veryfying connection settings, in my case the port for certificateAuthorities was 17054, but should have been 17062 from exported connection profile
> 
> hope it helps

@BayramAnnakov solution worked for me... the exported connection profile had 17050, but the connection.json in web-app had 17054 (change this to 17050).

**Comment by kokirieducare** [comment]
As mentioned - use the VSCode Blockchain extension as below 1.039 and VSCode latest Version: 1.52.1

node --version
v12.7.0
npm --version 
6.10.0
docker --version
Docker version 20.10.2, build 2291f61
java --version
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)



Please note : this problem will occurs using **VSCode Blockchain extension 2.0** ( may not be ready yet ) which follows **Fabric2 lifecycle.** 


![image](https://user-images.githubusercontent.com/77999652/106424839-c2899c80-64c7-11eb-81d1-286dda4ab833.png)
