### ISSUE TITLE
Error while Member Registration

### ISSUE THREAD

**Issue by AnilRai** [IBM/customer-loyalty-program-hyperledger-fabric-VSCode#25]
I am getting the following error 

Using param - firstname: aaa lastname: bb email: aa@bb.com phonenumber: 1234567890 accountNumber: 100001 cardId: ac1
Valid Entries
Wallet path: /Users/abc/Desktop/BlockChain/customer-loyalty-program-hyperledger-fabric-VSCode/web-app/wallet
Error: fabric-ca request register failed with errors [[{"code":19,"message":"CA 'ca.org1.example.com' does not exist"}]]
    at IncomingMessage.response.on (/Users/avnirai/Desktop/BlockChain/customer-loyalty-program-hyperledger-fabric-VSCode/web-app/node_modules/fabric-client/node_modules/fabric-ca-client/lib/FabricCAClient.js:327:22)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by PatelPriyanka** [comment]
I have same error, Can someone please let me know hot to solve it ?
