### ISSUE TITLE
Getting Error while adding new Member during registration

### ISSUE THREAD

**Issue by singhrajgithub** [IBM/customer-loyalty-program-hyperledger-fabric-VSCode#3]
Hi Ashutosh,

I followed same steps as followed by you but i am stuck at step of adding new member registration and partner registration. While creating new member for the first time i am getting below error :

fabric-ca request register failed with errors [[{"code":19,"message":"CA 'ca.example.com' does not exist"}]]
fabric-ca request register failed with errors [[{"code":19,"message":"CA 'ca.example.com' does not exist"}]]

Please find attached snapshot for the same.

Thanks

![Screenshot from 2019-05-16 11-01-53](https://user-images.githubusercontent.com/24280813/57876467-3b176980-77ca-11e9-99a4-391d6388b317.png)

Refer below for terminal logs 

app running on port: 8000
Using param - firstname: raj lastname: singh email: raj@example.com phonenumber: 5555555555 accountNumber: 100000 cardId: ac1
Valid Entries
Wallet path: /home/raaz/hyperledger/customer-loyalty-program-hyperledger-fabric-VSCode/web-app/wallet
Error: fabric-ca request register failed with errors [[{"code":19,"message":"CA 'ca.example.com' does not exist"}]]
    at IncomingMessage.response.on (/home/raaz/hyperledger/customer-loyalty-program-hyperledger-fabric-VSCode/web-app/node_modules/fabric-ca-client/lib/FabricCAClient.js:327:22)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
Using param - name: ibm@example.com partnerId: part1 cardId: ac1
Company name must be letters only
Using param - name: ibm partnerId: part1 cardId: ac1
Valid Entries
Wallet path: /home/raaz/hyperledger/customer-loyalty-program-hyperledger-fabric-VSCode/web-app/wallet
Error: fabric-ca request register failed with errors [[{"code":19,"message":"CA 'ca.example.com' does not exist"}]]
    at IncomingMessage.response.on (/home/raaz/hyperledger/customer-loyalty-program-hyperledger-fabric-VSCode/web-app/node_modules/fabric-ca-client/lib/FabricCAClient.js:327:22)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by lucianosilva44** [comment]
Hello, singhrajgithub,

Tested the project here, it had the same error. What is happening is that the name of the CA organization in the **connections.json** and **config.json** files do not match of the one automatically created by VSCode Blockchain Extension (they are writen as **ca.example.com**, while the org is created as **ca.org1.example.com**).
I'll make a pull request to Ashtosh right now to modify these details. If you wish, you can make the changes on your own and test now (only five lines of modification).

**Comment by ash7594** [comment]
Thanks for clarifying the error @lucianosilva44

**Comment by singhrajgithub** [comment]
Thanks @lucianosilva44 . I will update these and will give a try to run.

**Comment by ash7594** [comment]
Error is now fixed.

**Comment by AnilRai** [comment]
I am getting this error while adding member 

Error: fabric-ca request register failed with errors [[{"code":19,"message":"CA 'ca.org1.example.com' does not exist"}]]
    at IncomingMessage.response.on (/Users/avnirai/Desktop/BlockChain/customer-loyalty-program-hyperledger-fabric-VSCode/web-app/node_modules/fabric-client/node_modules/fabric-ca-client/lib/FabricCAClient.js:327:22)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by PatelPriyanka** [comment]
I am having the same error while trying to add member or partner. I could not solve it 
Even I check the name in connections.JSON file and config.json file. 
Can someone please let me know how to solve it.
![Error_img](https://user-images.githubusercontent.com/17672443/91797558-da938200-ebf0-11ea-9210-fdd0967fcc63.jpeg)
